version: '3'

services:

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
     - ./src:/var/www/html

  db:
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
     - dbdata:/var/lib/mysql

networks:
  backend:

volumes:
  dbdata:
    driver: "local"
