version: '3'

services:

  app:
    image: drewjs/dockpress
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SECURE}:443"
    networks:
      - backend

  db:
    image: mariadb:10.3
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend

networks:
  backend:
